before_install: 
 - cd SpringBootMySQLApp
 - chmod +x mvnw
 - mysql -e 'create database filmoteka;'
sudo: required
dist: trusty
services:
  - mysql
language: java
jdk:
 - oraclejdk8
 install: true
 addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

